# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20170617_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='hex_code',
        ),
    ]
