# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20170617_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
