# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 03:41
from __future__ import unicode_literals

import cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20170617_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='slot_number',
            field=models.IntegerField(blank=True, default=cars.models.get_slot_number, null=True),
        ),
    ]
