# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20170618_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=100)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.Car')),
            ],
        ),
    ]
