# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='slot_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
